language: android
android:
 components:
    - tools
    - build-tools-34.0.0
    - android-34

jdk: openjdk17

script:
  - ./gradlew build

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
