buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
    }
}

allprojects {
    tasks.withType(Test).configureEach {
        maxParallelForks = 4
        forkEvery = 100
        reports.html.required = false
        reports.junitXml.required = false
    }

    repositories {
        mavenCentral()
        google()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.layout.buildDirectory
}
